name: Build

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            triple: aarch64-apple-darwin
          - os: ubuntu-22.04
            triple: x86_64-unknown-linux-gnu
            runs-on: self-hosted
    runs-on: ${{ matrix.runs-on || matrix.os }}
    steps:
      - name: Install macos dependencies
        if: matrix.os == 'macos-14'
        run: |
          brew install jq curl libomp protobuf openssl nasm pkgconf open-mpi libffi nlohmann-json libsodium
          brew tap riscv-software-src/riscv
          brew install riscv-tools

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils jq curl build-essential qemu-system libomp-dev \
              libgmp-dev nlohmann-json3-dev protobuf-compiler uuid-dev libgrpc++-dev \
              libsecp256k1-dev libsodium-dev libpqxx-dev nasm libopenmpi-dev openmpi-bin openmpi-common

      - name: Install rust toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: lukka/get-cmake@v3.27.4

      - name: Show rust version
        run: |
          cargo version
          rustup toolchain list

      - name: Check out 0xPolygonHermez/zisk
        uses: actions/checkout@v3
        with:
          repository: 0xPolygonHermez/zisk
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: fix/build-toolchain
          path: zisk

      - name: Check out 0xPolygonHermez/rust
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          path: rust
          fetch-depth: 0

      - name: Prepare TMPDIR for gha
        run: |
          set -euxo pipefail
          TMP_DIR=/tmp/gha
          sudo install -d -o gha -g gha -m 0775 "$TMP_DIR"
          echo "TMPDIR=$TMP_DIR" >> "$GITHUB_ENV"

      - name: Build
        run: GITHUB_ACTIONS=false ZISK_BUILD_DIR=$GITHUB_WORKSPACE cargo run --bin cargo-zisk -- sdk build-toolchain
        working-directory: zisk

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: rust-toolchain-${{ matrix.triple }}
          path: |
            zisk/rust-toolchain-${{ matrix.triple }}.tar.gz
